<?php

namespace Gadi\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuotaGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotaGroupeRepository extends EntityRepository
{
}
