# src/Gadi/SiteBundle/Resources/config/routing.yml
 
gadisite_accueil:
    pattern:   /{page}
    defaults:  { _controller: GadiSiteBundle:Site:index, page: 1 }
    requirements:
        page:  \d*
     
gadisite_voir:
    pattern:   /voir/{type}
    defaults:  { _controller: GadiSiteBundle:Site:voir }	
    requirements:
        format: cours|quotagroupe|enseignant

gadisite_voir_cours:
    pattern:   /cours/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirCours }	
    requirements:
        id:  \d+

gadisite_voir_enseignant:
    pattern:   /enseignant/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirEnseignant }	
    requirements:
        id:  \d+	

gadisite_voir_etudiant:
    pattern:   /etudiant/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirEtudiant }	
    requirements:
        id:  \d+		
gadisite_voir_groupe:
    pattern:   /groupe/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirGroupe }	
    requirements:
        id:  \d+		

gadisite_voir_quota_enseignant:
    pattern:   /quotaenseignant/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirQuotaenseignant }
    requirements:
        id:  \d+		

gadisite_voir_module:
    pattern:   /module/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirModule }	
    requirements:
        id:  \d+		

gadisite_voir_quota_groupe:
    pattern:   /quotagroupe/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirQuotaGroupe }	
    requirements:
        id:  \d+

gadisite_modifier:
    pattern:   /modifier/{type}
    defaults:  { _controller: GadiSiteBundle:Site:modifier }
    requirements:
        format: enseignant|etudiant|module

gadisite_ajouter:
    pattern:   /ajouter/{type}
    defaults:  { _controller: GadiSiteBundle:Site:ajouter }
    requirements:
        format: enseignant|etudiant
