# src/Gadi/SiteBundle/Resources/config/routing.yml
 
gadisite_accueil:
    pattern:   /{page}
    defaults:  { _controller: GadiSiteBundle:Site:index, page: 1 }
    requirements:
        page:  \d*
     
gadisite_voir:
    pattern:   /voir/{type}
    defaults:  { _controller: GadiSiteBundle:Site:voir }	
    requirements:
        format: cours|quotagroupe

gadisite_voir_cours:
    pattern:   /cours/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirCours }	
    requirements:
        id:  \d+

gadisite_voir_cours:
    pattern:   /enseignant/{id}
    defaults:  { _controller: GadiSiteBundle:Site:voirEnseignant }	
    requirements:
        id:  \d+	
     
gadisite_ajouter:
    pattern:   /ajouter/{type}
    defaults:  { _controller: GadiSiteBundle:Site:ajouter }
    requirements:
        format: enseignant|etudiant